In [12]:
# this use all subjects with behav data (including those with no brain imaging data)

## read features:
import numpy as np
import pandas as pd

data_dir="/home/xin/Dropbox/BrainImaging_ML/data"
atlas_dir="/home/xin/Dropbox/BrainImaging_ML/Atlas_label"
work_dir="/home/xin/Dropbox/BrainImaging_ML/multidimensional_age_prediction/"

figure_dir = "/home/xin/Dropbox/BrainImaging_ML/multidimensional_age_prediction/figures_robustreg_behav_hc2"
result_dir = "/home/xin/Dropbox/BrainImaging_ML/multidimensional_age_prediction/result_robustreg_behav_hc2"

import os
from os import path
#trying to make result directory if it does not already exist:

if not os.path.exists(figure_dir):
    os.mkdir(figure_dir)
    
if not os.path.exists(result_dir):
    os.mkdir(result_dir)


In [13]:
cog_label_acc = [
    # executive control:
    "pcet_acc2",
    "pcpt_t_tp",
    "lnb_tp2",
    # episodic memory task:
    "pwmt_kiwrd_tot",
    "pfmt_ifac_tot",
    "volt_svt",
    # complex cognitive task:
    "pvrt_cr",
    "pmat_cr",
    "plot_tc",
    # social cognition task:
    "peit_cr",
    "pedt_a",
    "padt_a"
]

cog_label_speed = [
    # executive control:
    "pcet_rtcr",
    "pcpt_t_tprt",
    "lnb_rtc2",
    # episodic memory task:
    "pwmt_kiwrd_rtc",
    "pfmt_ifac_rtc",
    "volt_svtcrt",
    # complex cognitive task:
    "pvrt_rtcr",
    "pmat_rtcr",
    "plot_tcrt",
    # social cognition task:
    "peit_crt",
    "pedt_t",
    "padt_t",
    # sensorimotor speed task:
    "mp_mp2rtcr",
    "tap_tot"
]

cog_label_acc2 = [
    # executive control:
    "ABF",
    "ATT",
    "WM",
    # episodic memory task:
    "VMEM",
    "FMEM",
    "SMEM",
    # complex cognitive task:
    "LAN",
    "NVR",
    "SPA",
    # social cognition task:
    "EID",
    "EDI",
    "ADI"
]

cog_label_speed2 = [
    # executive control:
    "ABF",
    "ATT",
    "WM",
    # episodic memory task:
    "VMEM",
    "FMEM",
    "SMEM",
    # complex cognitive task:
    "LAN",
    "NVR",
    "SPA",
    # social cognition task:
    "EID",
    "EDI",
    "ADI",
    # sensorimotor speed task:
    "MOT",
    "SM"
]

cog_score_label = cog_label_acc + cog_label_speed
cog_score_label2 = [s + '_Accuracy' for s in cog_label_acc2] + [s + '_Speed' for s in cog_label_speed2]
num_cog = len(cog_score_label)

In [14]:
# select mental healthy subjects:
behav_data = pd.read_csv(data_dir+"/pyresult01_pnc_behav_mental3.csv", delimiter = ",")
hc_subject = behav_data.loc[behav_data['mental_hc1']==True, 'SUBJID']

behav_data = behav_data.loc[behav_data["SUBJID"].isin(hc_subject), ['SUBJID', 'Sex', 'age_at_cnb'] 
                            + cog_score_label]

#subject_info_feature['Sex'] = subject_info_feature['Sex'].apply({'F':0, 'M':1}.get)
# code females as -1 for easy interpretation of beta for age and age2
behav_data['Sex'] = behav_data['Sex'].apply({'F':-1, 'M':1}.get)

# reverse speed scores:
behav_data.loc[:,cog_label_speed] = behav_data.loc[:,cog_label_speed]*-1

#normalize the feature columns:
behav_data.loc[:,cog_score_label] = (behav_data.loc[:,cog_score_label] - behav_data.loc[:,cog_score_label].min()) / \
                        (behav_data.loc[:,cog_score_label].max() - behav_data.loc[:,cog_score_label].min())

num_subjects = behav_data.shape[0]
print(behav_data.columns)
behav_data.columns.values[3:] = cog_score_label2

behav_data.to_csv(result_dir+'/out01_behav_hc1.csv')

behav_data

# count number of NaNs:
# row_nancount = subject_info_feature.isna().sum()
# subject_info_feature = subject_info_feature.loc[:, subject_info_feature.isna().sum()==0]


Index(['SUBJID', 'Sex', 'age_at_cnb', 'pcet_acc2', 'pcpt_t_tp', 'lnb_tp2',
       'pwmt_kiwrd_tot', 'pfmt_ifac_tot', 'volt_svt', 'pvrt_cr', 'pmat_cr',
       'plot_tc', 'peit_cr', 'pedt_a', 'padt_a', 'pcet_rtcr', 'pcpt_t_tprt',
       'lnb_rtc2', 'pwmt_kiwrd_rtc', 'pfmt_ifac_rtc', 'volt_svtcrt',
       'pvrt_rtcr', 'pmat_rtcr', 'plot_tcrt', 'peit_crt', 'pedt_t', 'padt_t',
       'mp_mp2rtcr', 'tap_tot'],
      dtype='object')


SUBJID  Sex  age_at_cnb  ABF_Accuracy  ATT_Accuracy  WM_Accuracy  \
13    6.000156e+11   -1        18.0      0.761463      0.962963          1.0   
18    6.000204e+11    1        17.0      0.831262      0.944444          0.9   
20    6.000207e+11   -1        19.0      0.463374      0.944444          1.0   
33    6.000390e+11    1        11.0      0.885264      0.888889          0.8   
40    6.000429e+11   -1        13.0      0.836547      0.777778          0.9   
...            ...  ...         ...           ...           ...          ...   
8485  6.099538e+11    1         8.0      0.421890      0.537037          0.8   
8495  6.099749e+11   -1         9.0      0.282943      0.648148          0.9   
8504  6.099839e+11    1        11.0      0.621394      0.888889          0.5   
8508  6.099877e+11    1        15.0      0.711536      0.814815          1.0   
8515  6.099938e+11    1         9.0      0.549145      0.796296          1.0   

      VMEM_Accuracy  FMEM_Accuracy  SMEM_Accuracy  LAN_Accuracy  ...  \
13         0.807692       0.772727       0.750000      0.928571  ...   
18         0.884615       0.636364       0.666667      1.000000  ...   
20         0.653846       0.500000       0.416667      0.928571  ...   
33         1.000000       0.545455       0.833333      0.714286  ...   
40         0.807692       0.636364       0.833333      0.714286  ...   
...             ...            ...            ...           ...  ...   
8485       0.807692       0.818182       0.333333      0.714286  ...   
8495       0.923077       0.181818       0.666667      0.214286  ...   
8504       0.846154       0.681818       0.583333      0.571429  ...   
8508       0.884615       0.545455       0.916667      1.000000  ...   
8515       0.807692       0.545455       0.333333      0.571429  ...   

      FMEM_Speed  SMEM_Speed  LAN_Speed  NVR_Speed  SPA_Speed  EID_Speed  \
13      0.844807    0.826248   0.801951   0.776106   0.814040   0.918148   
18      0.771360    0.822546   0.859837   0.938058   0.847979   0.843513   
20      0.819914    0.885479   0.872382   0.926517   0.801179   0.882943   
33      0.926228    0.836757   0.796337   0.972613   0.858490   0.846682   
40      0.853170    0.849176   0.865412   0.956196   0.927724   0.883119   
...          ...         ...        ...        ...        ...        ...   
8485    0.722935    0.718295   0.647075   0.722523   0.831168   0.649534   
8495    0.800207    0.759494   0.776048   0.943734   0.825271   0.777152   
8504    0.888435    0.904586   0.813722   0.962442   0.954238   0.805492   
8508    0.613510    0.772749   0.851473   0.805055   0.776035   0.790002   
8515    0.688189    0.749821   0.838773   0.906967   0.829063   0.600246   

      EDI_Speed  ADI_Speed  MOT_Speed  SM_Speed  
13     0.735314   0.876294   0.879032  0.243781  
18     0.887620   0.906234   0.888861  0.358209  
20     0.790385   0.934609   0.957409  0.288557  
33     0.808743   0.865346   0.927167  0.589552  
40     0.949575   0.909064   0.919355  0.492537  
...         ...        ...        ...       ...  
8485   0.736175   0.819245   0.836946  0.567164  
8495   0.776044   0.808818   0.854839  0.589552  
8504   0.732561   0.803754   0.929435  0.320896  
8508   0.789353   0.453340   0.782258  0.460199  
8515   0.700838   0.739406   0.865171  0.514925  

[967 rows x 29 columns]

In [4]:
# multimodal_features

feature_beta_df = pd.DataFrame(index = cog_score_label2, 
                               columns = ['age', 'age$^2$', 'gender', 'age*gender', 'age*gender$^2$', 'Rsquare'])

# feature_beta_df = pd.DataFrame(index = multimodal_features.columns[1:], 
#                                columns = ['c_m', 'k_m', 'x0_m', 'y0_m',\
#                                           'c_f', 'k_f', 'x0_f', 'y0_f',\
#                                           'Rsquare'])

Rsquare_col = feature_beta_df.shape[1]


In [5]:
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
from sklearn.linear_model import RidgeCV
from sklearn.linear_model import RANSACRegressor
from sklearn.linear_model import HuberRegressor
from sklearn.linear_model import LinearRegression
from scipy import stats


# scaler = MinMaxScaler()
scaler = RobustScaler()

# scaler.fit(subject_info_feature.iloc[:,3:].values)
# subject_info_feature.iloc[:,3:] = scaler.transform(subject_info_feature.iloc[:,3:].values)

# alpha = np.power(10, np.linspace(-1, 3, num = 50))
# ridge_cv = RidgeCV(alphas=alpha, cv = 5)

lr = LinearRegression()

# as robust scaler scales the data by IQR, we set the residualthreshold to 1.5
robust_reg = RANSACRegressor(base_estimator = lr, min_samples=.8, residual_threshold = 1.5,
                             stop_probability=.99, stop_n_inliers = num_subjects*.9)

# robust_reg = HuberRegressor(epsilon=1.35, max_iter=100, alpha=0.0001, 
#                             warm_start=False, fit_intercept=True, tol=1e-05)

scaler.fit(behav_data.iloc[:,3:].values)
behav_data.iloc[:,3:] = scaler.transform(behav_data.iloc[:,3:].values)


for i_feature, i_feature2 in zip(cog_score_label, cog_score_label2):
    print(i_feature)
    
    gender = behav_data['Sex'].values
    chro_age = behav_data['age_at_cnb'].values
    feature = behav_data[i_feature].values
    
    # remove NaNs
    nan_idx = np.isnan(feature)
    gender = gender[~nan_idx]
    chro_age = chro_age[~nan_idx]
    feature = feature[~nan_idx]
    
#     # remove outliers:
#     X = np.transpose(np.vstack((chro_age, feature, gender)))
#     remove_idx = find_outlier(X)
    
    X = np.transpose(np.vstack((chro_age, chro_age**2, gender, chro_age*gender, (chro_age**2)*gender)))
    y = feature
    
############################################## ridge CV:########################################

#     # remove outliers based on the residuals of ridge regression:
#     clf = ridge_cv.fit(X, y)
#     residuals = y-clf.predict(X)
#     remove_idx = find_outlier(residuals)
    
#     # scale y with outlier removed:
#     scaler.fit(y[~remove_idx].reshape(-1,1))
#     y = scaler.transform(y.reshape(-1,1))
    
#     clf = ridge_cv.fit(X[~remove_idx,:], y[~remove_idx].flatten())
#     r2 = clf.score(X[~remove_idx,:], y[~remove_idx]) 
#     feature_beta_df.iloc[i_feature,1:] = np.hstack((clf.coef_, r2))

############################################ robust regression: #################################

    # scale the feature with inliers:
#     robust_reg.fit(X, y)
#     inlier_mask = np.logical_not(robust_reg.outliers_)
#     inlier_mask = robust_reg.inlier_mask_
#     scaler.fit(y[inlier_mask].reshape(-1,1))
#     y = scaler.transform(y.reshape(-1,1)).flatten()

    lr_all = lr.fit(X, y)
    # robust regression:
    robust_reg.fit(X, y)
    
#     inlier_mask = np.logical_not(robust_reg.outliers_)
    inlier_mask = robust_reg.inlier_mask_
    outlier_mask = np.logical_not(inlier_mask)
    coefs = robust_reg.estimator_.coef_
    
    # fit linear regression inliers and get the p-values of coefficients:
    lr.fit(X[inlier_mask,:], y[inlier_mask])
    params = np.append(lr.intercept_,lr.coef_)
    predictions = lr.predict(X[inlier_mask,:])
    
    # calculate p values:
    newX = np.append(np.ones((len(X[inlier_mask,:]),1)), X[inlier_mask,:], axis=1)
    MSE = (sum((y[inlier_mask]-predictions)**2))/(len(newX)-len(newX[0]))

    var_b = MSE*(np.linalg.inv(np.dot(newX.T,newX)).diagonal())
    sd_b = np.sqrt(var_b)
    ts_b = params/ sd_b

    p_values =np.array([2*(1-stats.t.cdf(np.abs(i),(len(newX)-1))) for i in ts_b])
    
    # compare the coefs of lr (with inliers) and ransac, which should be same
    print(coefs)
    print(lr.coef_)
    
    # coefs[p_values[1:]>0.05]==0 # it's weird that this does not work!!!!
    # np.place(coefs, p_values[1:]>.05, 0)
    # print(coefs)
    
    r2 = robust_reg.score(X, y) 
    
    print(np.hstack((coefs, r2)))
    feature_beta_df.loc[i_feature2,:] = np.hstack((coefs, r2))
#     feature_beta_df.iloc[i_feature,1:] = np.hstack((robust_reg.coef_, r2))
    
############################################# make regression plots:#############################
    plot_age = np.arange(5,26, step = 1)
    plot_gender = np.ones(21)
    
    plot_x_male = np.transpose(np.vstack((plot_age, plot_age**2, plot_gender, 
                                          plot_age*plot_gender, (plot_age**2)*plot_gender)))
    
    plot_x_female = np.transpose(np.vstack((plot_age, plot_age**2, -plot_gender,
                                            plot_age*-plot_gender, (plot_age**2)*-plot_gender)))
    
    y_curve_male = lr_all.predict(plot_x_male)
    y_curve_female = lr_all.predict(plot_x_female)
    
#     y_curve_male = lr_all.predict(plot_x_male)
#     y_curve_female = lr_all.predict(plot_x_female)
    
    y_curve_male_ransac = robust_reg.predict(plot_x_male)
    y_curve_female_ransac = robust_reg.predict(plot_x_female)
    
#     y_curve_male_ransac = robust_reg.predict(plot_x_male)
#     y_curve_female_ransac = robust_reg.predict(plot_x_female)
    
    label = "$R^2$ = %.3f" % r2

    fig = plt.figure()
    ax = fig.add_subplot(111)    
    
    ax.plot(plot_age, y_curve_female, 'r--')
    ax.plot(plot_age, y_curve_male, 'b--')
    
    ax.plot(plot_age, y_curve_female_ransac, 'r-')
    ax.plot(plot_age, y_curve_male_ransac, 'b-')
    
    idx = np.logical_and(gender==-1, outlier_mask)
    ax.plot(chro_age[idx]+np.random.random(sum(idx))*.3, y[idx], 
            'r+', markersize = 2.5)
    
    idx = np.logical_and(gender==-1, inlier_mask)
    ax.plot(chro_age[idx]+np.random.random(sum(idx))*.3, y[idx], 
            'ro', label='females', markersize = 2.5)
    
    idx = np.logical_and(gender==1, outlier_mask)
    ax.plot(chro_age[idx]+np.random.random(sum(idx))*.3, y[idx], 
            'b+', markersize = 2.5)
    
    idx = np.logical_and(gender==1, inlier_mask)
    ax.plot(chro_age[idx]+np.random.random(sum(idx))*.3, y[idx], 
            'bo', label='males', markersize = 2.5)
    
    ax.text(8, max(y), label, fontsize = 10)
    y_label = i_feature2
    if len(y_label)>20:
        y_label = y_label[:20]

    ax.set_ylabel(y_label)

    ax.legend()
    fig.savefig(figure_dir+'/figure_scatter_age_behav_' + i_feature2 + '.jpg', format = 'jpg', dpi=300)
    plt.close('all')

        
############################################## sigmoid fit:########################################
#     try:
#         feature_beta_df.iloc[i_feature,1:] = sigmoid_fit(chro_age, gender, feature)

#         x = np.linspace(6, 23, num=30)
#         y_fit_m = sigmoid2(x, feature_beta_df.iloc[i_feature,1],feature_beta_df.iloc[i_feature,2],
#                            feature_beta_df.iloc[i_feature,3],feature_beta_df.iloc[i_feature,4])

#         y_fit_f = sigmoid2(x, feature_beta_df.iloc[i_feature,5],feature_beta_df.iloc[i_feature,6],
#                            feature_beta_df.iloc[i_feature,7],feature_beta_df.iloc[i_feature,8])

#         fig = plt.figure()
#         ax = fig.add_subplot(111)    
#         ax.plot(x, y_fit_m, 'b--', label='male')
#         ax.plot(x, y_fit_f, 'r--', label='female')

#         male_idx = subject_info_feature.iloc[:,1]==1
#         female_idx = subject_info_feature.iloc[:,1]!=1

#         ax.plot(subject_info_feature.loc[male_idx].iloc[:,2],
#                 subject_info_feature.loc[male_idx].iloc[:,i_feature+3], 'bo')

#         ax.plot(subject_info_feature.loc[female_idx].iloc[:,2],
#                 subject_info_feature.loc[female_idx].iloc[:,i_feature+3],'ro')

#         ax.legend()
#         fig.savefig(figure_dir+'/figure_scatter_age_feature_sigmoid2fit_' +
#                    feature_beta_df.iloc[i_feature, 0] + str(i_feature) + '.jpg', format = 'jpg', dpi=300)
#         plt.close('all')

#         print(feature_beta_df.iloc[i_feature,1:])
#     except:
#         fig = plt.figure()
#         ax = fig.add_subplot(111)    

#         male_idx = subject_info_feature.iloc[:,1]==1
#         female_idx = subject_info_feature.iloc[:,1]!=1

#         ax.plot(subject_info_feature.loc[male_idx].iloc[:,2],
#                 subject_info_feature.loc[male_idx].iloc[:,i_feature+3], 'bo')

#         ax.plot(subject_info_feature.loc[female_idx].iloc[:,2],
#                 subject_info_feature.loc[female_idx].iloc[:,i_feature+3],'ro')

#         ax.legend()
#         fig.savefig(figure_dir+'/figure_scatter_age_feature_sigmoid2fit_fail_' +
#                    feature_beta_df.iloc[i_feature, 0] + str(i_feature) + '.jpg', format = 'jpg', dpi=300)
#         plt.close('all')
    
    

pcet_acc2
[ 0.17804561 -0.00507213  0.2931651  -0.02973661  0.00063837]
[ 0.17804561 -0.00507213  0.2931651  -0.02973661  0.00063837]
[ 0.17804561 -0.00507213  0.2931651  -0.02973661  0.00063837  0.04368805]
pcpt_t_tp
[ 2.94209608e-01 -7.60707074e-03  7.73724326e-02 -8.70756732e-03
  2.91565377e-04]
[ 2.94209608e-01 -7.60707074e-03  7.73724326e-02 -8.70756732e-03
  2.91565377e-04]
[ 2.94209608e-01 -7.60707074e-03  7.73724326e-02 -8.70756732e-03
  2.91565377e-04  1.42593112e-01]
lnb_tp2
[ 0.24488455 -0.00684204 -0.06647159  0.01222966 -0.0004174 ]
[ 0.24488455 -0.00684204 -0.06647159  0.01222966 -0.0004174 ]
[ 0.24488455 -0.00684204 -0.06647159  0.01222966 -0.0004174   0.17777058]
pwmt_kiwrd_tot
[ 1.70029321e-02  1.92841723e-04 -2.89928898e-01  3.22677944e-02
 -1.02811252e-03]
[ 1.70029321e-02  1.92841723e-04 -2.89928898e-01  3.22677944e-02
 -1.02811252e-03]
[ 1.70029321e-02  1.92841723e-04 -2.89928898e-01  3.22677944e-02
 -1.02811252e-03 -2.88715613e-02]
pfmt_ifac_tot
[ 0.35080394 -0.0

In [6]:
print(p_values)
coefs[np.where(p_values[1:]>.15)]==0
np.where(p_values[1:]>.15)

[0.00000000e+00 0.00000000e+00 3.28572725e-11 8.99063355e-01
 9.82137705e-01 7.46196000e-01]


(array([2, 3, 4]),)

In [11]:
# feature_beta_df.to_csv(result_dir+'/feature_beta_sigmoid2.csv')
feature_beta_df.to_csv(result_dir+'/behave_beta_ransac_lr.csv')
# feature_beta_df.to_csv(result_dir+'/feature_beta_huber.csv')

In [8]:
# clf.alpha_

In [9]:
# x=np.array([[1,2,3],[np.nan, 2,4]])
# np.isnan(x).any(axis=1)
feature_beta_df.iloc[22,1:].isnull().any()

False

In [10]:
feature_beta_df

age      age$^2$     gender   age*gender age*gender$^2$  \
ABF_Accuracy    0.178046  -0.00507213   0.293165   -0.0297366    0.000638372   
ATT_Accuracy     0.29421  -0.00760707  0.0773724  -0.00870757    0.000291565   
WM_Accuracy     0.244885  -0.00684204 -0.0664716    0.0122297   -0.000417395   
VMEM_Accuracy  0.0170029  0.000192842  -0.289929    0.0322678    -0.00102811   
FMEM_Accuracy   0.350804   -0.0104286    0.19122   -0.0287719    0.000840501   
SMEM_Accuracy   0.196173  -0.00646877   0.618676   -0.0914178     0.00325327   
LAN_Accuracy     0.46421   -0.0131659   0.445753   -0.0668671     0.00250482   
NVR_Accuracy    0.299991   -0.0078114   0.424656     -0.05984     0.00224085   
SPA_Accuracy     0.47304   -0.0159285   0.274188   -0.0291224     0.00132039   
EID_Accuracy    0.308443  -0.00951097   0.346428   -0.0432459     0.00117968   
EDI_Accuracy   -0.354918    0.0200259   -1.13617     0.189527    -0.00837368   
ADI_Accuracy   -0.373266    0.0214588   -1.99088     0.351345     -0.0152274   
ABF_Speed       0.309341  -0.00996607   0.661315   -0.0802514      0.0022318   
ATT_Speed       0.484657   -0.0131753  0.0323511   0.00202674   -0.000173959   
WM_Speed        0.211841  -0.00607079   0.999553    -0.134408      0.0045242   
VMEM_Speed      0.375901   -0.0100516   0.166001    -0.028973     0.00102351   
FMEM_Speed      0.216642  -0.00602432   0.132209  -0.00726037    -0.00014338   
SMEM_Speed      0.232697  -0.00632369   0.907966    -0.131647     0.00451557   
LAN_Speed       0.564957   -0.0179375   0.676472   -0.0956517     0.00296305   
NVR_Speed       0.157395  -0.00665397   0.329616   -0.0453046       0.001139   
SPA_Speed       0.241606  -0.00909279   0.458779   -0.0547432     0.00174453   
EID_Speed       0.352601   -0.0100627  0.0162484   -0.0054013   -4.18127e-05   
EDI_Speed       0.202945  -0.00563677     0.3057   -0.0296219    0.000397177   
ADI_Speed       0.140472   -0.0037958   0.318219   -0.0284094    0.000233185   
MOT_Speed       0.272439  -0.00791424  -0.107647    0.0157275   -0.000280904   
SM_Speed       -0.360807   0.00860087 -0.0301436  0.000808874   -0.000414759   

                  Rsquare  
ABF_Accuracy     0.043688  
ATT_Accuracy     0.142593  
WM_Accuracy      0.177771  
VMEM_Accuracy  -0.0288716  
FMEM_Accuracy    0.126538  
SMEM_Accuracy   0.0359837  
LAN_Accuracy     0.296185  
NVR_Accuracy     0.164364  
SPA_Accuracy     0.207396  
EID_Accuracy    0.0824746  
EDI_Accuracy     0.481657  
ADI_Accuracy     0.502718  
ABF_Speed      0.00755068  
ATT_Speed         0.42114  
WM_Speed        0.0755486  
VMEM_Speed       0.187707  
FMEM_Speed      0.0301901  
SMEM_Speed       0.056679  
LAN_Speed        0.141156  
NVR_Speed     -0.00799575  
SPA_Speed       0.0113524  
EID_Speed        0.133538  
EDI_Speed       0.0312241  
ADI_Speed      0.00531049  
MOT_Speed       0.0231816  
SM_Speed          0.39162